package manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import model.Account;

public class AccountManager {
	private Connection conn;
	private Statement stmt;
	
	public AccountManager(){
		try {
			conn = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/projekt");
			stmt = conn.createStatement();
			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Account".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			if (!tableExists) stmt.executeUpdate("CREATE TABLE Account(idAccount int UNIQUE GENERATED BY DEFAULT AS IDENTITY, login UNIQUE varchar(30), password varchar(25), registrationDate date, lastLogin date)");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Connection getConnection() {
		return conn;
	}
	
	public void addAccount(Account account){
		
	}
	
	public void deleteCharacter(Account account){
		
	}
	
	public List<Account> getAll(){
		List<Account> accounts = new ArrayList<Account>();
		
		return accounts;
	}
}
