package manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class CharacterListManager {
	//"SELECT a.login, c.nick, c.characterclass, c.characterrace, c.level FROM characterList as cl left join account as a on cl.idAccount=a.idAccount left join character as c on c.idCharacter=cl.idCharacter where idAccount=1;"
	private Connection conn;
	private Statement stmt;
	
	public CharacterListManager(){
		try {
			conn = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/projekt");
			stmt = conn.createStatement();
			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("CharacterList".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			if (!tableExists) stmt.executeUpdate("CREATE TABLE CharacterList(idCharacterList int UNIQUE GENERATED BY DEFAULT AS IDENTITY, idAccount int, idCharacter int, foreign key (idAccount) references account(idAccount), foreign key (idCharacter) references character(idCharacter))");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Connection getConnection() {
		return conn;
	}
}
